import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Taskbar from "../components/Sidebar";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased flex overflow-x-hidden`}>
        <Taskbar />
        <main className="flex-1  w-full h-screen">{children}</main>
      </body>
    </html>
  );
}
